name: flutter_document_picker_example
description: Demonstrates how to use the flutter_document_picker plugin.

version: 1.0.0+1

environment:
  flutter: ^3.24.3
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_document_picker:
    path: ../

flutter:
  uses-material-design: true


