name: flutter_document_picker
description: Allows user pick a document. Picked document is copied to app temporary directory. Optionally allows pick document with specific extension only.
version: 5.2.3
homepage: https://github.com/sidlatau/flutter_document_picker

environment:
  flutter: ^3.24.3
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.sidlatau.flutterdocumentpicker
        pluginClass: FlutterDocumentPickerPlugin
      ios:
        pluginClass: FlutterDocumentPickerPlugin
